#include "common.inc"

#include "MPlayDef.inc"
#include "asm_m4a.inc"
#include "asm_music_voice.inc"

.section .rodata

#if CONFIG_DEBUG_M4A_TEST

.global voicegroup_08381254
voicegroup_08381254: @ 08381254
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, wav_0839A844, 0x40, 0x00, 0xFF, 0xA5
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, wav_0839CE98, 0xFF, 0x00, 0xFF, 0xA5
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, wav_0839EFFC, 0xFF, 0x00, 0xFF, 0xA5
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, wav_0839F824, 0x40, 0x00, 0xFF, 0xA5
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_keysplit_all voicegroup_083931AC

.global voicegroup_083931AC
voicegroup_083931AC: @ 083931AC
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, wav_083A9750, 0xFF, 0x00, 0xFF, 0x7F
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, wav_0839A844, 0xFF, 0x00, 0xFF, 0x7F
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, wav_083D23C8, 0xFF, 0x00, 0xFF, 0x7F
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, wav_083A5518, 0xFF, 0x7F, 0xE7, 0xA5
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, wav_083C9280, 0xFF, 0x00, 0xFF, 0x7F
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, wav_083EC748, 0xFF, 0x00, 0xFF, 0x7F
    voice_directsound_no_resample 60, 0, wav_08404390, 0xFF, 0x00, 0xFF, 0xCC
    voice_directsound_no_resample 60, 0, wav_08405BE4, 0xFF, 0x00, 0xFF, 0xCC
    voice_directsound_no_resample 60, 0, wav_08405ED8, 0xFF, 0x00, 0xFF, 0xCC
    voice_directsound_no_resample 60, 0, wav_08406B58, 0xFF, 0x00, 0xFF, 0xCC
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_directsound_no_resample 60, 0, wav_08409304, 0xFF, 0x00, 0xFF, 0xCC
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_directsound_no_resample 60, 0, wav_083BFA6C, 0xFF, 0x00, 0xFF, 0xCC
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0
    voice_square_1 0, 2, 0, 0, 15, 0

#endif /* CONFIG_DEBUG_M4A_TEST */
