#pragma once

#include "common.h"
#include "banim.h"
#include "banimdrv.h"

enum video_banim {
    BGPAL_EFX_0 = 0,
    BGPAL_EFX_SPELL_BG = 1,
    BGPAL_EFX_2 = 2,
    BGPAL_EFX_3 = 3,
    BGPAL_EFX_4 = 4,
    BGPAL_EFXDRAGON_L = 6,
    BGPAL_EFXDRAGON_R = 7,

    OBPAL_EFX_SYSTEM_OBJ = 0,
    OBPAL_EFX_SPELL_BG = 1,
    OBPAL_EFX_SPELL_OBJ = 2,
    OBPAL_EFX_FACE = 3,
    OBPAL_EFX_5 = 5,
    OBPAL_EFX_BG = 6,
    OBPAL_EFX_UNIT_L = 7,
    OBPAL_EFX_UNIT_BAK_L = 8,
    OBPAL_EFX_UNIT_R = 9,
    OBPAL_EFX_UNIT_BAK_R = 10,
    OBPAL_EFXHPBAR_L = 11,
    OBPAL_EFXHPBAR_R = 12,
    OBPAL_EFX_ITEM_L = 13,
    OBPAL_EFX_ITEM_R = 14,

    VRAMOFF_BANIM_SPELL_OBJ = 0x0800,
    VRAMOFF_BANIM_SPELL_BG  = 0x2000,
    VRAMOFF_BANIM_8000 = 0x8000,

    VRAMOFF_OBJ_EKRGAUGE_SUBFIX = 0x3800,
    VRAMOFF_OBJ_EKRGAUGE_NUM_L  = 0x3A00,
    VRAMOFF_OBJ_EKRGAUGE_ICON_L = 0x3B80,
    VRAMOFF_OBJ_EKRGAUGE_ICON_R = 0x3BC0,
    VRAMOFF_OBJ_EKRGAUGE_ARROW  = 0x3C00,
    VRAMOFF_OBJ_EKRGAUGE_NUM_R  = 0x3E00,
    VRAMOFF_OBJ_4000            = 0x4000,
    VRAMOFF_OBJ_6000            = 0x6000,

    VRAMOFF_BG_EKRLVUP_FONT = 0x2400,
};

enum ekr_hit {
    EKR_HITTED = 0,
    EKR_MISS
};

enum banim_sprites_size {
    BAS_SCR_MAX_SIZE = 0x2A00,
    BAS_OAM_MAX_SIZE = 0x5800,
    BAS_IMG_MAX_SIZE = 0x1000,

    BAS_OAM_REF_MAX_SIZE = BAS_OAM_MAX_SIZE - 0x10,
};

extern u8 gBanimScrs[2 * BAS_SCR_MAX_SIZE];
extern u8 gBanimOamBufs[2 * BAS_OAM_MAX_SIZE];
extern u8 gBanimImgSheetBufs[2 * BAS_IMG_MAX_SIZE];

enum anim_round_type {
    ANIM_ROUND_BIT8 = 0x0100,
    ANIM_ROUND_PIERCE = 0x0200,
    ANIM_ROUND_GREAT_SHIELD = 0x0400,
    ANIM_ROUND_SURE_SHOT = 0x0800,
    ANIM_ROUND_SILENCER = 0x1000,
    ANIM_ROUND_POISON = 0x2000,
    ANIM_ROUND_BIT14 = 0x4000,
    ANIM_ROUND_DEVIL = 0x8000,    
};

enum banim_mode_index {
    BANIM_MODE_NORMAL_ATK,
    BANIM_MODE_NORMAL_ATK_PRIORITY_L,
    BANIM_MODE_CRIT_ATK,
    BANIM_MODE_CRIT_ATK_PRIORITY_L,
    BANIM_MODE_RANGED_ATK,
    BANIM_MODE_RANGED_CRIT_ATK,
    BANIM_MODE_CLOSE_DODGE,
    BANIM_MODE_RANGED_DODGE,
    BANIM_MODE_STANDING,
    BANIM_MODE_STANDING2,
    BANIM_MODE_RANGED_STANDING,
    BANIM_MODE_MISSED_ATK,

    BANIM_MODE_INVALID = -1,
};

extern const u8 BanimDefaultModeConfig[ANIM_ROUND_MAX * 4];

void NewEkrChienCHR(struct Anim *anim);
void SyncBanimImage(struct Anim *anim);
